import type { Database } from "./types";

export function seedDatabase(): Database {
  return {
    restaurantName: "Le Comptoir",
    categories: [
      { id: "entrees", name: "Entrées", position: 1 },
      { id: "plats", name: "Plats", position: 2 },
      { id: "desserts", name: "Desserts", position: 3 },
      { id: "boissons", name: "Boissons", position: 4 },
    ],
    menu: [
      {
        id: "burrata",
        categoryId: "entrees",
        name: "Burrata crémeuse",
        description: "Tomates anciennes, basilic, huile d'olive vierge extra",
        price: 9.5,
        available: true,
      },
      {
        id: "soupe",
        categoryId: "entrees",
        name: "Velouté de saison",
        description: "Légumes du marché, croûtons maison",
        price: 7,
        available: true,
      },
      {
        id: "tartare",
        categoryId: "entrees",
        name: "Tartare de saumon",
        description: "Aneth, citron vert, blinis tièdes",
        price: 11,
        available: true,
      },
      {
        id: "entrecote",
        categoryId: "plats",
        name: "Entrecôte grillée",
        description: "Frites maison, beurre d'herbes, salade",
        price: 22,
        available: true,
      },
      {
        id: "risotto",
        categoryId: "plats",
        name: "Risotto aux champignons",
        description: "Champignons de Paris, parmesan affiné 24 mois",
        price: 17.5,
        available: true,
      },
      {
        id: "poisson",
        categoryId: "plats",
        name: "Filet de dorade",
        description: "Écrasé de pommes de terre, sauce vierge",
        price: 19.5,
        available: true,
      },
      {
        id: "burger",
        categoryId: "plats",
        name: "Burger du comptoir",
        description: "Bœuf charolais, cheddar, oignons confits, frites",
        price: 16,
        available: true,
      },
      {
        id: "fondant",
        categoryId: "desserts",
        name: "Fondant au chocolat",
        description: "Cœur coulant, glace vanille de Madagascar",
        price: 8,
        available: true,
      },
      {
        id: "tarte",
        categoryId: "desserts",
        name: "Tarte du jour",
        description: "Préparée chaque matin par le chef pâtissier",
        price: 7,
        available: true,
      },
      {
        id: "cafe",
        categoryId: "boissons",
        name: "Café expresso",
        description: "Torréfaction artisanale",
        price: 2.5,
        available: true,
      },
      {
        id: "limonade",
        categoryId: "boissons",
        name: "Limonade maison",
        description: "Citron pressé, menthe fraîche",
        price: 4.5,
        available: true,
      },
      {
        id: "vin",
        categoryId: "boissons",
        name: "Verre de vin rouge",
        description: "Côtes-du-Rhône, 12 cl",
        price: 5.5,
        available: true,
      },
    ],
    tables: [
      { id: "1", name: "Table 1" },
      { id: "2", name: "Table 2" },
      { id: "3", name: "Table 3" },
      { id: "4", name: "Table 4" },
      { id: "5", name: "Table 5" },
      { id: "6", name: "Table 6" },
    ],
    orders: [],
  };
}
